version: "3.4"

services:
  oracle-local:
    image: container-registry.oracle.com/database/free
    container_name: oracle-local
    ports:
      - "1521:1521"
      - "4000:4000"
      - "5500:5500"
