set serveroutput on;
DROP PROCEDURE IF EXISTS print_person_name_in_range;
DROP TABLE IF EXISTS person;
CREATE TABLE person (
    id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT current_timestamp,
    PRIMARY KEY (id)
);
INSERT INTO person (name)
VALUES ('Peter');
INSERT INTO person (name)
VALUES ('Mary');
INSERT INTO person (name)
VALUES ('Julia');
INSERT INTO person (name)
VALUES ('Hans');
INSERT INTO person (name)
VALUES ('Carl');
COMMIT;
CREATE OR REPLACE PROCEDURE print_person_name_in_range (p_begin IN LONG, p_end IN LONG) AS CURSOR c_person IS
SELECT id,
    name,
    created_at
FROM person
WHERE id BETWEEN p_begin AND p_end;
BEGIN FOR current_person IN c_person LOOP dbms_output.put_line(current_person.name);
END LOOP;
END;
/
DECLARE BEGIN print_person_name_in_range(0, 3);
END;
-- add test data
INSERT INTO PERSON (ID, NAME, CREATED)
VALUES (1, 'John', DEFAULT);
INSERT INTO PERSON (ID, NAME, CREATED)
VALUES (2, 'Mary', DEFAULT);
COMMIT;
-- iterate over cursor with while loop
DECLARE CURSOR c_person IS
SELECT "ID",
    "NAME",
    "CREATED"
FROM PERSON;
v_person_data c_person %ROWTYPE;
BEGIN DBMS_OUTPUT.PUT_LINE('Start...');
OPEN c_person;
FETCH c_person into v_person_data;
WHILE c_person %FOUND loop DBMS_OUTPUT.PUT_LINE(
    v_person_data."NAME" || ' ' || v_person_data."CREATED"
);
FETCH c_person into v_person_data;
end loop;
close c_person;
commit;
END;
/ -- iterate over cursor with for loop
DECLARE CURSOR c_person IS
SELECT "ID",
    "NAME",
    "CREATED"
FROM PERSON;
BEGIN DBMS_OUTPUT.PUT_LINE('Start...');
FOR v_person_data IN c_person loop DBMS_OUTPUT.PUT_LINE(
    v_person_data."NAME" || ' ' || v_person_data."CREATED"
);
end loop;
commit;
END;
/